# Generated by Django 3.2.8 on 2021-10-09 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMapModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60, verbose_name='タイトル')),
                ('overview', models.TextField(blank=True, max_length=250, null=True, verbose_name='概要')),
                ('is_public', models.CharField(choices=[('public', '公開'), ('private', '非公開')], default='private', max_length=50, verbose_name='公開・非公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_learn', models.TextField(blank=True, max_length=100, null=True, verbose_name='やること')),
                ('is_completed', models.CharField(choices=[('left_untouched', '未着手'), ('going', '途中'), ('is_completed', '完了')], max_length=50, verbose_name='進捗')),
                ('order', models.IntegerField(verbose_name='順番')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='roadmap.roadmapmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LookBackModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learned', models.TextField(blank=True, max_length=1000, null=True, verbose_name='学習したこと')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookBack', to='roadmap.stepmodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
